name: Gatsby Publish

on:
  schedule:
    # Every Monday at 1PM UTC (9AM EST)
    - cron: "0 13 * * 1" 
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: master